In [3]:
import numpy as numpy

In [4]:
myList = numpy.arange(0,15)

In [5]:
myList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
myList[5]

5

In [7]:
myList[3:8]

array([3, 4, 5, 6, 7])

In [8]:
myList

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
newArray = numpy.random.randint(1,100,20)

In [10]:
newArray

array([41, 60, 45, 61, 61, 24, 90, 45, 48, 60, 62,  6, 28,  2, 67, 73, 67,
       93, 25, 58])

In [12]:
newArray > 24

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True])

In [13]:
resultArray = newArray > 24

In [14]:
resultArray

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True])

In [15]:
newArray

array([41, 60, 45, 61, 61, 24, 90, 45, 48, 60, 62,  6, 28,  2, 67, 73, 67,
       93, 25, 58])

In [17]:
newArray[resultArray] # only greater than 24

array([41, 60, 45, 61, 61, 90, 45, 48, 60, 62, 28, 67, 73, 67, 93, 25, 58])

In [19]:
newArray[newArray > 24]

array([41, 60, 45, 61, 61, 90, 45, 48, 60, 62, 28, 67, 73, 67, 93, 25, 58])

In [21]:
lastArray = numpy.arange(0,24)

In [23]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [27]:
numpy.sqrt(lastArray) #karekok

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [28]:
numpy.max(lastArray)

23

In [29]:
numpy.min(lastArray)

0